{
	"version": 1607269251,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/background.png",
		"images/solidtile.png",
		"images/player-sheet0.png",
		"images/jumpthrutile.png",
		"images/movingsolidtile.png",
		"images/door_closed-sheet0.png",
		"images/door_open-sheet0.png",
		"images/star-sheet0.png",
		"images/lives-sheet0.png",
		"images/lives-sheet1.png",
		"images/spikes-sheet0.png",
		"images/blood.png",
		"images/bg.png",
		"images/box-sheet0.png",
		"images/overlaper-sheet0.png",
		"images/pausebutton-sheet0.png",
		"images/pausebutton-sheet1.png",
		"images/sprite-sheet0.png",
		"images/mutebutton-sheet0.png",
		"images/mutebutton-sheet1.png",
		"images/border-sheet0.png",
		"images/border-sheet1.png",
		"images/healthbar-sheet0.png",
		"media/death.ogg",
		"media/game_over.ogg",
		"media/jump.ogg",
		"media/pickup coin.ogg",
		"media/door open.ogg"
	]
}